package com.mycompany.myapp;


import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;import static com.codename1.io.Log.e;
import com.codename1.ui.Button;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionListener;
import java.io.IOException;
import com.codename1.media.MediaManager;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi World");
        hi.addComponent(new Label("Hi World"));
        Button b = new Button("Play Ellink");
        hi.add(b);
        String destUIID = null;
        //ActionListener e;
        //Player play;
        b.addActionListener((e)->Dialog.show("Playing Ellink","Ellie is Here","Close",null));
        b.addActionListener((e)->Dialog.show("Playing Ellink","Ellie is Here","Close",null));
        //b.createStyleAnimation(destUIID, 3);
        hi.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

//    
//    public static void main(String...arg)
//    {
//        try
//        {
//        new MyApplication().start();
//        }catch(Exception ex)
//        {
//            
//        }
//    }
//    
    
}
